### ISSUE TITLE
Possible to use a subset of this in combination with Vimwiki?

### ISSUE THREAD

**Issue by jondkinney** [reedes/vim-pencil#45]
Hi there!

I love Pencil, and I'd like to use some of the features (hard wrap at 80 chars at least) when editing my Vimwiki, but if I do that some of the auto-formatting on `<cr>`, amongst other things breaks for that filetype which means things like new todo list entries don't get created, for example.

Any idea if it's possible to do the hard wrap portion of this plugin in a [vimwiki](https://github.com/vimwiki/vimwiki) context?

Thanks!

**Comment by reedes** [comment]
Glad you like it!

I'm not familiar with vimwiki, but if the need is only to disable auto-formatting for certain highlight groups, we can extend the blacklist to for the filetype.

Also, with the #43 changes, pencil should no longer touch an existing `<cr>` insert mode mapping if one is present, if that's relevant to vimwiki's operation.

**Comment by alerque** [comment]
A little bit of review suggests that this issue is probably fixed, per #43. I would be happy to re-open in for review if there is any ongoing problem in relation to this. I would also love to see a contribution from somebody that has set Pencil up with blacklists as described to play nicely with vimwiki or any other plugins in the form of documentation on exactly how they did so. I think that would be useful to keep in the README to save future users the trouble figuring out which options are relevant. And of course if there is anything we can change to make compatibility easier out of the box we can look into that too!
