### ISSUE TITLE
hard wrap does not handle code blocks well in markdown

### ISSUE THREAD

**Issue by chenhouwu** [reedes/vim-pencil#48]
when in hard wrap mode, I can't input exactly as the following:

    ```
    this is a code block
    ```

Pencil will auto reposition `this is a code block` to the end of the first *```*

**Comment by reedes** [comment]
A difficult problem to address, as when you enter Insert mode you're not yet in a blacklisted highlight group, which would disable autoformat.

As a workaround, I'd suggest manually disabling autoformat with a mapping per the README...

```
noremap <silent> <F7> :<C-u>PFormatToggle<cr>
inoremap <silent> <F7> <C-o>:PFormatToggle<cr>
```

It'd be nice to have an alternative way to enter Insert mode where autoformat would be automatically disabled. Keeping this open to explore that.

**Comment by cpdean** [comment]
additionally, markdown lists get messed up by the auto linewrap stuff :/

**Comment by reedes** [comment]
There's at least one separate issue (#37, e.g.) for the lists. It's a separate problem because Vim's autoformat will handle them properly in certain configurations, but not in others.

The code block issue is a matter of having a good mechanism of disabling Vim's autoformat for the duration of the Insert.

**Comment by reedes** [comment]
New optional buffer-scoped modifier key mapping will ideally offer the additional control desired to suspend autoformat for the Insert.
