### ISSUE TITLE
YAML Auto-formatting in Auto Mode

### ISSUE THREAD

**Issue by raysome** [reedes/vim-pencil#54]
Is it possible to add support to automatically disable default autofomatting when recognising YAML header in markdown file? Since it tries to format YAML header to one line in auto mode. And it is pretty annoying to switch modes manually.

**Comment by reedes** [comment]
Does the YAML have a syntax highlight group? If so, it can be added to the blacklist, which prevents autoformat from being enabled when you enter insert mode.

Here's a key mapping you can use to determine the highlight groups at the current cursor position

```
nmap <F9> :call <SID>SynStack()<CR>
function! <SID>SynStack()
  if !exists("*synstack")
    return
  endif
  echo map(synstack(line('.'), col('.')), 'synIDattr(v:val, "name")')
endfunc
```

**Comment by giseray** [comment]
Hi @reedes, Thanks for your patient reply.

Specifically, I came across this problem in using pandoc-extended markdown file. I have installed `vim-pandoc` and `vim-pandoc-syntax` plugins, and when I open a markdown file, it is recognized as a 'pandoc' file.

According to your guide, I have found the syntax highlight group for yaml in pandoc-extended markdown, i.e. `pandocYAMLHeader`, and I have added it to `~/plugin/pencil.vim`, shown as follow:

```VIM
if !exists('g:pencil#autoformat_config')
  let g:pencil#autoformat_config = {

...

        \   'pandoc': {
        \     'black': [
        \       'pandoc(pandocYAMLHeader)',
        \       'pandoc(pandocDelimitedCodeBlock)',
        \     ],
        \   },
        \ }
en
```

But unfortunately it still doesn't work. Is there anything wrong with my procedures?

BTW, is it possible to add new items to blacklists in `_vimrc` instead of change the `~/plugin/pencil.vim` file?

**Comment by reedes** [comment]
You can define your own blacklist in your vimrc. Just copy the whole g:pencil#autoformat_config global declaration, or the parts you care about, from pencil.vim.

Unfortunately I won't be able to dig into this anytime soon. Feel free to record any progress you make here.

**Comment by alerque** [comment]
This appears to have been fixed as YAML blocks are not reformatted for me here and I see that `pandocYAMLHeader` has made it into the default blacklist.

If there are any further issues related to this please feel free to comment and I'd be happy to re-evaluate.
