### ISSUE TITLE
Unexpected behavior with SoftPencil  and Visual Block

### ISSUE THREAD

**Issue by xaviervalarino** [reedes/vim-pencil#68]
When using `:SoftPencil` with `V-BLOCK`, I get some unexpected behavior.

I use `V-BLOCK` often to select a range of text and then add something to the end of each line.

As an example, if I want to add a comma after each line of the _lorem ipsum_ shown below, I'll visually select the range and append a comma.

So the keystrokes would be: `<C-v> G $ `:

![screen shot 2018-03-30 at 11 07 09 am](https://user-images.githubusercontent.com/4262486/38148345-ea2df0ec-340a-11e8-9124-5571cc3c3ce5.png)

Followed by: ` A , <Esc> `:

![screen shot 2018-03-30 at 11 07 44 am](https://user-images.githubusercontent.com/4262486/38148346-ea59f9b2-340a-11e8-8159-307f4bc933d6.png)

But, when I have `Soft Pencil` enabled, `V-Block` selects all the way to the end.

![screen shot 2018-03-30 at 11 08 34 am](https://user-images.githubusercontent.com/4262486/38148347-ea9dc368-340a-11e8-935c-f860cce47730.png)

Obviously I can simply run `:PencilOff` beforehand, but I usually have to actually make the selection before I remember what's going on.

**Comment by alerque** [comment]
This appears to have been caused by `$` still being mapped to the hard end of line (which is soft mode is basically end of paragraph). I've fixed that mapping in #82 and I think this will work as you expect now. At least your example does for me as best I can mimic it.

Please feel free to comment back and re-open this is for some reason it doesn't work right.
