### ISSUE TITLE
Why is textwidth not used for soft wrap?

### ISSUE THREAD

**Issue by stevenroose** [reedes/vim-pencil#80]

**Comment by mikemc** [comment]
It seems that the reason is that vim does not support soft wrapping at a set text width. See the discussion at https://stackoverflow.com/questions/989093/soft-wrap-at-80-characters-in-vim-in-window-of-arbitrary-width and https://github.com/neovim/neovim/issues/4386

I agree that soft wrapping at `textwidth` would be very useful and it is bizarre to me that vim doesn't support it.

**Comment by alerque** [comment]
This issue is pretty much held-up by upstream implementation. I don't think Pencil can do anything about it. A poor-man fix is described in the SO question linked above:

```vim
set columns=80
autocmd VimResized * if (&columns > 80) | set columns=80 | endif
```

...but that will only work for some terminal situations. It works with Neovim inside tmux inside Termite, but will probably mess with your window in many Terminals. When upstream VIM or Neovim supports this it will naturally also filter down to Pencil users.

If anybody is extra eger for this I would suggest sponsoring a bounty on the Neovim issue (Bountysource was supported last I checked).
