### ISSUE TITLE
SoftPencil seems doesn't work

### ISSUE THREAD

**Issue by mgdreamingstar** [reedes/vim-pencil#87]
Is the soft wrap mode just wrap on screen as `set wrap` do?
Does this plugin can do more than vim itself on soft wrap, such as set a linewidth for soft wrap other than buffer border?

**Comment by alerque** [comment]
Ne, it is not _just_ an alias for `set wrap`. It does turn on the soft wrap mode, but it does a much of other things too including adjust how many of the navigation keystrokes work so that they default to the `g` visual counterparts (`j` becomes `gj` etc.). It also does things like set undo points at punctuation characters, enables various conceal behaviors, etc.

No there is no way to set a virtual width other than the buffer border (although there are ways to set the buffer width independently to be smaller than the window width if that's what you are after). There is such a thing in Hard mode, but not Soft.

**Comment by mgdreamingstar** [comment]
Could you tell me how to set buffer width independently?

**Comment by alerque** [comment]
Not off the top of my head, and it's out of scope for this issue. I do something similar using the GoYo vim plugin. You could look into the source of how that does it. Otherwise ask on vi.stackexchange.com as I believe there is a way to force the buffer width to be different than what the terminal reports, but I don't remember what it is.
